"""fourth version

Revision ID: 1503c4c51cfd
Revises: b9ecbd8fc4db
Create Date: 2025-06-05 15:36:07.261926

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1503c4c51cfd'
down_revision = 'b9ecbd8fc4db'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('solusi',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('penyakit_id', sa.String(length=5), nullable=False),
    sa.Column('skala', sa.String(length=10), nullable=False),
    sa.Column('solusi', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['penyakit_id'], ['penyakit.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('solusi')
    # ### end Alembic commands ###
