"""third version

Revision ID: b9ecbd8fc4db
Revises: fbc06660d918
Create Date: 2025-06-02 17:14:10.745798

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b9ecbd8fc4db'
down_revision = 'fbc06660d918'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('diagnosa', schema=None) as batch_op:
        batch_op.add_column(sa.Column('gejala_skoring', sa.Text(), nullable=False))

    with op.batch_alter_table('gejala', schema=None) as batch_op:
        batch_op.add_column(sa.Column('kategori', sa.String(length=50), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('gejala', schema=None) as batch_op:
        batch_op.drop_column('kategori')

    with op.batch_alter_table('diagnosa', schema=None) as batch_op:
        batch_op.drop_column('gejala_skoring')

    # ### end Alembic commands ###
