"""tambah informasi pribadi user

Revision ID: c531cb18e5b2
Revises: 1503c4c51cfd
Create Date: 2025-06-07 17:43:57.540458

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c531cb18e5b2'
down_revision = '1503c4c51cfd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('diagnosa', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nama', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('umur', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('anak_ke', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('usia_kehamilan', sa.Integer(), nullable=False))
        batch_op.drop_constraint('diagnosa_ibfk_2', type_='foreignkey')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('diagnosa', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('diagnosa_ibfk_2', 'user', ['user_id'], ['id'])
        batch_op.drop_column('usia_kehamilan')
        batch_op.drop_column('anak_ke')
        batch_op.drop_column('umur')
        batch_op.drop_column('nama')

    # ### end Alembic commands ###
