"""second migrate

Revision ID: fbc06660d918
Revises: f91eeedf8edb
Create Date: 2025-05-26 15:08:25.772823

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fbc06660d918'
down_revision = 'f91eeedf8edb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gejala',
    sa.Column('id', sa.String(length=5), nullable=False),
    sa.Column('nama', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('penyakit',
    sa.Column('id', sa.String(length=5), nullable=False),
    sa.Column('nama', sa.String(length=50), nullable=False),
    sa.Column('deskripsi', sa.Text(), nullable=True),
    sa.Column('threshold', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('diagnosa',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('tanggal', sa.DateTime(), nullable=True),
    sa.Column('penyakit_id', sa.String(length=5), nullable=False),
    sa.Column('skor_total', sa.Float(), nullable=False),
    sa.Column('gejala_terpenuhi', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['penyakit_id'], ['penyakit.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rule_gejala',
    sa.Column('penyakit_id', sa.String(length=5), nullable=False),
    sa.Column('gejala_id', sa.String(length=5), nullable=False),
    sa.Column('bobot', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['gejala_id'], ['gejala.id'], ),
    sa.ForeignKeyConstraint(['penyakit_id'], ['penyakit.id'], ),
    sa.PrimaryKeyConstraint('penyakit_id', 'gejala_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rule_gejala')
    op.drop_table('diagnosa')
    op.drop_table('penyakit')
    op.drop_table('gejala')
    # ### end Alembic commands ###
